In [2]:
#LAB2:Working with arrays using Jupyter
#1) Convert the list into numpy array then display the array
#input: my_list=[1,2,3,4,5]
#output:Numpy array:[1 2 3 4 5]

import numpy as np

my_list=[1,2,3,4,5]
arr=np.array(my_list)
print("Numpy array",arr)


Numpy array [1 2 3 4 5]


In [3]:
#2)convert the below list into a numpy array then display the array, then display the first and last index and 
#then multiply each element by 2 and display the result
#input:my_list=[1,2,3,4,5]
#output: First element: 1
#Last element: 5
#Array after doubling each element:
#[2 4 6 8 10]

my_list=[1,2,3,4,5]
arr=np.array(my_list)
print("Numpy array:",arr)
print("First Element:",arr[0])
print("Last Element:",arr[4])
print("Array after doubling each element:",arr*2)

Numpy array [1 2 3 4 5]
First Element 1
Last Element 5
Array after doubling each element [ 2  4  6  8 10]


In [8]:
#LAB3:Working with Numpy using Jupyter
#1)Write a numpy program to create an array of 10 zeros, 10 ones and 10 fives.
#Sample Output:
#An array of 10 zeros:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#An array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
#An array of 10 fives:[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

a=np.zeros(10)
print("An array of 10 zeros: \n",a)
b=np.ones(10)
print("An array of 10 ones:\n",b)
c=np.ones(10)*5
print("An array of 10 fives:\n",c)


An array of 10 zeros: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [18]:
#2)Write a Numpy program to create a 3*3 matrix with values ranging from 2 to 10.

rand= np.random.randint(2,10,9)       #using random numbers
arr=rand.reshape(3,3)
print(arr)


[[7 8 3]
 [2 3 3]
 [9 4 7]]


In [16]:
arr2=[2,3,4,5,6,7,8,9,10]         #or by providing numbers as input
arr=np.array(arr2)
arr=arr.reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
