In [2]:
#Suppose you have a dataset containing daily temperature readings for a city, and you want to identify days with extreme temperature conditions. 
#Find days where the temperature either exceeded 35 degrees Celsius (hot day) or dropped below 5 degrees Celsius (cold day).

import numpy as np
temperatures = np.array([32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2, 4.0, 22.6, 15.7, -4.0, -12.0])

# Find hot days (temperatures > 35 degrees Celsius)
hot_days = np.where(temperatures > 35)[0] + 1  # Adding 1 to convert 0-based index to 1-based day
hot_temperatures = temperatures[temperatures > 35]

# Find cold days (temperatures < 5 degrees Celsius)
cold_days = np.where(temperatures < 5)[0] + 1  # Adding 1 to convert 0-based index to 1-based day
cold_temperatures = temperatures[temperatures < 5]

print("Hot Days:")
print("Day     Temperature(C)")
for day, temp in zip(hot_days, hot_temperatures):             #Iterating through hot days
    print(f"{day:<7} {temp:.1f}")

print("\nCold Days:")
print("Day     Temperature(C)")
for day, temp in zip(cold_days, cold_temperatures):                  #Iterating through cold days
    print(f"{day:<7} {temp:.1f}")


Hot Days:
Day     Temperature(C)
3       36.8
6       38.7
10      37.2

Cold Days:
Day     Temperature(C)
11      4.0
14      -4.0
15      -12.0


In [3]:
#suppose you have a dataset containing monthly sales data for a company, and you want to split this data into quaterly reports for analysis and 
#reporting purposes

monthly_sales=np.array([120,135,148,165,180,155,168,190,205,198,210,225])
sub_arrays=np.split(monthly_sales,4)              #splitting into 4 equal parts
i=1
for sub_arr in sub_arrays:
    print("Quarter", i, "sales(in thousands of dollars):")
    print(sub_arr)
    i=i+1

Quarter 1 sales(in thousands of dollars):
[120 135 148]
Quarter 2 sales(in thousands of dollars):
[165 180 155]
Quarter 3 sales(in thousands of dollars):
[168 190 205]
Quarter 4 sales(in thousands of dollars):
[198 210 225]


In [4]:
#Suppose you have a dataset cpontaining customer data, and you want to split this data into 2 groups: one group for customers who made a purchase in 
#the last 30 days and another group for customers who haven't made a purchase in the last 30 days

customer_ids=np.array([101,102,103,104,105,106,107,108,109,110])
last_purchase_days_ago=np.array([5,15,20,25,30,35,40,45,50,55])
purchased_last_30_days = customer_ids[last_purchase_days_ago <= 30]
not_purchased_last_30_days = customer_ids[last_purchase_days_ago > 30]
print("Active Customers (Last Purchase <= 30 days ago): ")
print(purchased_last_30_days)

print("Inactive Customers (Last Purchase > 30 days ago): ")
print(not_purchased_last_30_days)

Active Customers (Last Purchase <= 30 days ago): 
[101 102 103 104 105]
Inactive Customers (Last Purchase > 30 days ago): 
[106 107 108 109 110]


In [5]:
#Suppose you have two sets of employee data—one containing information about full-time employees and another containing information about
#part-time employees. You want to combine this data to create a comprehensive employee dataset for HR analysis.


# Employee data for full-time employees
full_time_employees = np.array([
[101, 'John Doe', 'Full-Time', 55000],
[102, 'Jane Smith', 'Full-Time', 60000],
[103, 'Mike Johnson', 'Full-Time', 52000]
])

# Employee data for part-time employees
part_time_employees = np.array([
[201, 'Alice Brown', 'Part-Time', 25000],
[202, 'Bob Wilson', 'Part-Time', 28000],
[203, 'Emily Davis', 'Part-Time', 22000]
])
result=np.vstack((full_time_employees,part_time_employees))
print("Combined Employee Data: ")
for employee in result:
    emp_id, name, emp_type, salary = employee
    print(f"Employee ID: {emp_id}, Name: {name}, Type: {emp_type}, Salary: {salary}")

Combined Employee Data: 
Employee ID: 101, Name: John Doe, Type: Full-Time, Salary: 55000
Employee ID: 102, Name: Jane Smith, Type: Full-Time, Salary: 60000
Employee ID: 103, Name: Mike Johnson, Type: Full-Time, Salary: 52000
Employee ID: 201, Name: Alice Brown, Type: Part-Time, Salary: 25000
Employee ID: 202, Name: Bob Wilson, Type: Part-Time, Salary: 28000
Employee ID: 203, Name: Emily Davis, Type: Part-Time, Salary: 22000


In [6]:
# How to find the mean of every NumPy array in the given list?

list = [
np.array([3, 2, 8, 9]),
np.array([4, 12, 34, 25, 78]),
np.array([23, 12, 67])
]
means = [float(np.mean(arr)) for arr in list]
print(f"Mean of each array:\n{means}")

Mean of each array:
[5.5, 30.6, 34.0]


In [7]:
#Compute the median of the flattened NumPy array

x_odd = np.array([1, 2, 3, 4, 5, 6, 7])
print("Printing the original array:")
print(x_odd)
print("Median of the array that contains odd no of elements:")
median_x = np.median(x_odd)
print(median_x)

Printing the original array:
[1 2 3 4 5 6 7]
Median of the array that contains odd no of elements:
4.0


In [8]:
#Compute the standard deviation of the NumPy array

arr = [20, 2, 7, 1, 34]
arr_mean=np.mean(arr)
arr_std=np.std(arr)
print("arr:",arr)
print("std of arr: ",arr_std)
std_dev = np.std(arr, dtype=np.float32)
print("\nMore precision with float32")
print("std of arr: ",std_dev)
std_dev2 = np.std(arr, dtype=np.float64)
print("\nMore accuracy with float64")
print("std of arr: ",std_dev2)

arr: [20, 2, 7, 1, 34]
std of arr:  12.576167937809991

More precision with float32
std of arr:  12.576168

More accuracy with float64
std of arr:  12.576167937809991


In [15]:
#Suppose you have a CSV file named 'house_prices.csv' with price information, and
#you want to perform the following operations:

import pandas as pd

# 1. Read the data from the CSV file into a Pandas DataFrame
filename = 'house_prices.csv'
df = pd.read_csv(filename)
data_array = df.to_numpy()               # Converting DataFrame to NumPy array
prices = data_array[:, 1]  # Extract prices from the array

# 2. Calculate the average of house prices
average_price = np.mean(prices)
print(f"Average house price: {average_price:.2f}")

print("\nHouse prices above average:")

# 3. Identify house prices above the average
high_prices = prices[prices > average_price]
high_prices_df = pd.DataFrame(high_prices, columns=['Price'])     # Preparing data for saving
print(high_prices_df)

# 4. Save the list of high prices to a new CSV file
high_prices_filename = 'high_prices.csv'
high_prices_df.to_csv(high_prices_filename, index=False)

print(f"List of high prices has been saved to {high_prices_filename}.")


Average house price: 7590.98

House prices above average:
               Price
0        11112.36771
1        8384.577435
2        9541.738987
3       12066.049417
4       11319.378999
...              ...
100062   9364.320352
100063  11035.416284
100064   8127.917844
100065   7685.277322
100066   8919.892685

[100067 rows x 1 columns]
List of high prices has been saved to high_prices.csv.
