In [2]:
import numpy as np

c=np.array([[1, 2, 3],[4, 5, 6],[4, 5, 6]])
print(np.diag(c))      #finding diagonal elements in the array
print(np.diag((3,9,5)))       #inserting elements diagonally


[1 5 6]
[[3 0 0]
 [0 9 0]
 [0 0 5]]


In [5]:
rand= np.random.randint(0,10,2)
print("Generates random 2 numbers between 0 to 10: ",rand)

rand=np.random.rand(4)    #generates an array of specific shape and fills it with random samples from a uniform distribution over the interval [0,1).
print("Generates 4 random numbers: ",rand)
rand=np.random.rand(2,3)
print("Generates 2 rows with 3 random numbers: ",rand)

arr=np.random.randint(0,100,12)
print("Generates random 12 numbers between 0 to 100: ",arr)


Generates random 2 numbers between 0 to 10:  [5 8]
Generates 4 random numbers:  [0.23080199 0.0131799  0.38595714 0.42536654]
Generates 2 rows with 3 random numbers:  [[0.90124379 0.11955781 0.85158678]
 [0.87189403 0.34093016 0.44513064]]
Generates random 12 numbers between 0 to 100:  [76 51 83 13 42  8 43 84 98 82 50 24]


In [7]:
'''this reshape function allows you to change the shape(dimensions) of an array without changing its data. this can be
useful when you want to rearrange the way data is organized in an array, such as converting a1D array into a 2D matrix, or
changing the size of a multi-dimensional array while maintaining the size'''

arr=np.random.randint(0,100,12)
print("Generates random 12 numbers between 0 to 100: ",arr)
arr=arr.reshape(4,3)
print("Array reshaped to shape(4,3):",arr)
print("Array value at index[0][1] is: ",arr[0][1])
print("Array value at index[1][0] is: ",arr[1][0])
print("Shape of the array is: ",arr.shape)
arr=arr.reshape(-1,4)                #it takes value of row accordingly
print("Array reshaped:",arr)         #need to specify 1 dimension atleast
arr=arr.reshape(2,-1)                #it takes value of column accordingly
print("Array reshaped:",arr)

Generates random 12 numbers between 0 to 100:  [17 68 96 45 22 19 77 90 48 14  7 85]
Array reshaped to shape(4,3): [[17 68 96]
 [45 22 19]
 [77 90 48]
 [14  7 85]]
Array value at index[0][1] is:  68
Array value at index[1][0] is:  45
Shape of the array is:  (4, 3)
Array reshaped: [[17 68 96 45]
 [22 19 77 90]
 [48 14  7 85]]
Array reshaped: [[17 68 96 45 22 19]
 [77 90 48 14  7 85]]


In [8]:
#the list of random numbers will be fixed
np.random.seed(145)
arr=np.random.randint(0,100,12)
print(arr)

[37 86 87 18 90 69  8 53 33 32 40 26]


In [24]:
np.random.seed(111)
arr=np.random.randint(1,500,30).reshape(6,5)
print(arr)

[[341 365 469 213  87]
 [276 170 323 119 467]
 [297 456 442   8 269]
 [267 450 369 217 285]
 [271 419  22  55 201]
 [ 38 461 231 187 269]]


In [26]:
print(arr[2:,2:])   #the row and column doesn't have any range so it will print till last
print()
print(arr[3:5,2:4])   #the row indexes are 3 to 4 and column indexes are 2 to 3

[[442   8 269]
 [369 217 285]
 [ 22  55 201]
 [231 187 269]]

[[369 217]
 [ 22  55]]


In [15]:
ar=np.array([1,20,5,9,3,4,8,5,6,2,25,2,2265,3,33,])
slicing=ar[4:9]
print("new slicing",slicing)
print("new array",ar)
print(type(slicing))
print(type(ar))
slicing[:]=0
print("old slicing",slicing)    #the old sliced numbers replaced by 0
print("old array",ar)         #the sliced elements replaced are now presented i

new slicing [3 4 8 5 6]
new array [   1   20    5    9    3    4    8    5    6    2   25    2 2265    3
   33]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
old slicing [0 0 0 0 0]
old array [   1   20    5    9    0    0    0    0    0    2   25    2 2265    3
   33]


In [21]:
#to create numbers in sequence we use arange function
ar=np.arange(1,15)
print("Array in sequence:",ar)
print("Even number array:",ar[ar%2==0])
print("Odd number array:",ar[ar%2!=0])
print("Array with numbers greater than 8:",ar[ar>8])
ar[ar%2==0]=0
print("Even numbers are replaced with 0:",ar)

arr=np.arange(1,8)
print("Adding 2 to every element:",arr+2)
print("Multiplying 2 to every element:",arr*2)
print("Power of every element:",arr**2)

Array in sequence: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Even number array: [ 2  4  6  8 10 12 14]
Odd number array: [ 1  3  5  7  9 11 13]
Array with numbers greater than 8: [ 9 10 11 12 13 14]
Even numbers are replaced with 0: [ 1  0  3  0  5  0  7  0  9  0 11  0 13  0]
Adding 2 to every element: [3 4 5 6 7 8 9]
Multiplying 2 to every element: [ 2  4  6  8 10 12 14]
Power of every element: [ 1  4  9 16 25 36 49]


In [29]:
arr=np.array([10,20,30,25,6,2])
print("Minimum number in array:",np.min(arr))
print("Maximum number in array:",np.max(arr))
print("Returns the index of the minimum number:",np.argmin(arr))
print("Returns the index of the maximum number:",np.argmax(arr))
print("Square root value of every element:",np.sqrt(arr))
print("Sin value:",np.sin(arr))
print("Cos value:",np.cos(arr))

Minimum number in array: 2
Maximum number in array: 30
Returns the index of the minimum number: 5
Returns the index of the maximum number: 2
Square root value of every element: [3.16227766 4.47213595 5.47722558 5.         2.44948974 1.41421356]
Sin value: [-0.54402111  0.91294525 -0.98803162 -0.13235175 -0.2794155   0.90929743]
Cos value: [-0.83907153  0.40808206  0.15425145  0.99120281  0.96017029 -0.41614684]


In [42]:
np.random.seed(122)
mat=np.random.randint(1,21,9).reshape(3,3)
print("Array of size(3,3):",mat)
print("Sum of elements of array:",np.sum(mat))
print("Adding numbers one by one:",np.cumsum(mat))
print("Finding minimum number from array:",np.min(mat))
print("Finding maximum number from array:",np.max(mat))
print("Computing the sum of elements along the columns of the matrix: ",np.sum(mat,axis=0))
print("Computing the minimum value along the columns of the matrix:",np.min(mat,axis=0))
print("Computing the maximum value along the columns of the matrix:",np.max(mat,axis=0))
print("Computing the cumulative sum along the columns:",np.cumsum(mat,axis=0))

Array of size(3,3): [[16 11 13]
 [17 13 16]
 [ 3 16 11]]
Sum of elements of array: 116
Adding numbers one by one: [ 16  27  40  57  70  86  89 105 116]
Finding minimum number from array: 3
Finding maximum number from array: 17
Computing the sum of elements along the columns of the matrix:  [36 40 40]
Computing the minimum value along the columns of the matrix: [ 3 11 11]
Computing the maximum value along the columns of the matrix: [17 16 16]
Computing the cumulative sum along the columns: [[16 11 13]
 [33 24 29]
 [36 40 40]]


In [43]:
np.random.seed(122)
mat=np.random.randint(1,21,10)
print("Matrix:",mat)
np.random.shuffle(mat)
print("Randomly shuffled:",mat)
print("Finding unique elements: ",np.unique(mat,return_index=True, return_counts=True))
print("Count of unique elements: ",np.unique(mat).size)

Matrix: [16 11 13 17 13 16  3 16 11 10]
Randomly shuffled: [13 16 16 11 16 10 11 13 17  3]
Finding unique elements:  (array([ 3, 10, 11, 13, 16, 17], dtype=int32), array([9, 5, 3, 0, 1, 8]), array([1, 1, 2, 2, 3, 1]))
Count of unique elements:  6
