In [7]:
import numpy as np
arr=np.array([3,4,7,1,5,6,2,8,9])         #if elements are less it will not adjust accordingly and will throw an error

[3 4 7]
[1 5 6]
[2 8 9]


In [9]:
sorted_arr=np.sort(arr)
print("Sorted array in ascending order",sorted_arr)
sorted_arr_desc=np.sort(arr)[::-1]
print("Sorted array in descending order",sorted_arr_desc)

Sorted array in ascending order [1 2 3 4 5 6 7 8 9]
Sorted array in descending order [9 8 7 6 5 4 3 2 1]


In [10]:
matrix=np.array([[3,1,2],[6,5,4]])
sorted_matrix=np.sort(matrix,axis=1)
print("Sorted matrix ascending along rows:",sorted_matrix)

Sorted matrix ascending along rows: [[1 2 3]
 [4 5 6]]


In [12]:
#Numpy Join
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.concatenate((arr1,arr2),axis=1)        # join arrays along a specified axis.
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [17]:
result=np.concatenate((arr1,arr2),axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
#Vertical Stacking
arr1=np.array([1,2,3])
arr2=np.array([5,6,7])
result=np.vstack((arr1,arr2))
print(result)

[[1 2 3]
 [5 6 7]]


In [19]:
#Horizontal Stacking
arr1=np.array([1,2,3])
arr2=np.array([5,6,7])
result=np.hstack((arr1,arr2))
print(result)

[1 2 3 5 6 7]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6])
mask = (arr > 2) & (arr < 6)
filtered_array = arr[mask]
print("Filtered Array:", filtered_array)


Filtered Array: [3 4 5]


In [23]:
prd_b= np.array([2,8])
prdB_var=np.var(prd_b)
print('Production B Variance',prdB_var)

Production B Variance 9.0


In [25]:
# Score of Class B students
classB= np.array([70, 80, 85, 95, 100])
classB_mean=np.mean(classB)
print('Class B Score Average is: ',classB_mean )
var=np.var(classB)
print("Variance of CLass B is: ",var)
std=np.std(classB)
print("Standard Deviation of CLass B is: ",std)

Class B Score Average is:  86.0
Variance of CLass B is:  114.0
Standard Deviation of CLass B is:  10.677078252031311


In [27]:
test_scores = np.array([65, 75, 80, 85, 90, 92, 94, 95, 96, 98, 100, 102, 104, 106, 108,
110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138])
median = np.percentile(test_scores, 50)           #median divides the data into two equal halves. It's the middle value when the data is sorted.
print("Median (50th Percentile):", median)
median = np.percentile(test_scores, 25)
print("Median (25th Percentile):", median)

Median (50th Percentile): 109.0
Median (25th Percentile): 95.25


In [28]:
#NumPy Input Output(IO)
# Sample student scores
scores = np.array([85, 92, 78, 88, 95, 72, 89])
# Save the scores to a file
np.save('student_scores.npy', scores)
# Load the scores from the file
loaded_scores = np.load('student_scores.npy')
print("Original Scores:", scores)
print("Loaded Scores:", loaded_scores)

Original Scores: [85 92 78 88 95 72 89]
Loaded Scores: [85 92 78 88 95 72 89]


In [29]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Save the data to a text file
np.savetxt('data.txt', data)
# Load the data from the text file
loaded_data = np.loadtxt('data.txt')
print("Original Data:\n", data)
print("Loaded Data:\n", loaded_data)

Original Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Loaded Data:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
